"""initial procurement schema

Revision ID: 98d40bd9e7ec
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '98d40bd9e7ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batch',
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_execution_log',
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_execution_log_tool_name'), 'tool_execution_log', ['tool_name'], unique=False)
    op.create_table('procurement_run',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('inventory_max_age_days', sa.Integer(), nullable=False),
    sa.Column('commercial_max_age_days', sa.Integer(), nullable=False),
    sa.Column('expected_sku_count', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('reorder_count', sa.Integer(), nullable=False),
    sa.Column('no_reorder_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku_master',
    sa.Column('sku_id', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('uom', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('target_stock', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'sku_id')
    )
    op.create_index(op.f('ix_sku_master_batch_id'), 'sku_master', ['batch_id'], unique=False)
    op.create_table('supplier_master',
    sa.Column('supplier_id', sa.String(length=80), nullable=False),
    sa.Column('supplier_name', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'supplier_id')
    )
    op.create_index(op.f('ix_supplier_master_batch_id'), 'supplier_master', ['batch_id'], unique=False)
    op.create_table('demand',
    sa.Column('sku_id', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('need_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id', 'sku_id'], ['sku_master.batch_id', 'sku_master.sku_id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_batch_id'), 'demand', ['batch_id'], unique=False)
    op.create_index(op.f('ix_demand_sku_id'), 'demand', ['sku_id'], unique=False)
    op.create_table('inventory_snapshot',
    sa.Column('sku_id', sa.String(length=80), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id', 'sku_id'], ['sku_master.batch_id', 'sku_master.sku_id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_snapshot_batch_id'), 'inventory_snapshot', ['batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshot_sku_id'), 'inventory_snapshot', ['sku_id'], unique=False)
    op.create_table('open_po',
    sa.Column('sku_id', sa.String(length=80), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id', 'sku_id'], ['sku_master.batch_id', 'sku_master.sku_id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_po_batch_id'), 'open_po', ['batch_id'], unique=False)
    op.create_index(op.f('ix_open_po_sku_id'), 'open_po', ['sku_id'], unique=False)
    op.create_table('po_draft',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=80), nullable=False),
    sa.Column('supplier_name', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=32, scale=2), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['procurement_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'supplier_id')
    )
    op.create_index(op.f('ix_po_draft_run_id'), 'po_draft', ['run_id'], unique=False)
    op.create_table('sku_check_result',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sku_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('on_hand', sa.BigInteger(), nullable=True),
    sa.Column('valid_incoming', sa.BigInteger(), nullable=True),
    sa.Column('demand_qty', sa.BigInteger(), nullable=True),
    sa.Column('projected_stock', sa.BigInteger(), nullable=True),
    sa.Column('raw_order_qty', sa.BigInteger(), nullable=True),
    sa.Column('final_order_qty', sa.BigInteger(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('NO_REORDER','REORDER','BLOCKED')"),
    sa.ForeignKeyConstraint(['run_id'], ['procurement_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sku_id')
    )
    op.create_index(op.f('ix_sku_check_result_run_id'), 'sku_check_result', ['run_id'], unique=False)
    op.create_table('supplier_sku',
    sa.Column('sku_id', sa.String(length=80), nullable=False),
    sa.Column('supplier_id', sa.String(length=80), nullable=True),
    sa.Column('approved_for_sku', sa.Boolean(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('moq', sa.Integer(), nullable=True),
    sa.Column('pack_multiple', sa.Integer(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id', 'sku_id'], ['sku_master.batch_id', 'sku_master.sku_id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_sku_batch_id'), 'supplier_sku', ['batch_id'], unique=False)
    op.create_index(op.f('ix_supplier_sku_sku_id'), 'supplier_sku', ['sku_id'], unique=False)
    op.create_table('approval_event',
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['po_draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_event_draft_id'), 'approval_event', ['draft_id'], unique=False)
    op.create_table('exception',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('required_field', sa.String(length=100), nullable=False),
    sa.Column('required_action', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['sku_check_result.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['procurement_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_result_id'), 'exception', ['result_id'], unique=False)
    op.create_index(op.f('ix_exception_run_id'), 'exception', ['run_id'], unique=False)
    op.create_table('po_line',
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('result_revision', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('uom', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=32, scale=2), nullable=False),
    sa.Column('need_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.CheckConstraint('unit_price > 0'),
    sa.ForeignKeyConstraint(['draft_id'], ['po_draft.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['sku_check_result.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id')
    )
    op.create_index(op.f('ix_po_line_draft_id'), 'po_line', ['draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_po_line_draft_id'), table_name='po_line')
    op.drop_table('po_line')
    op.drop_index(op.f('ix_exception_run_id'), table_name='exception')
    op.drop_index(op.f('ix_exception_result_id'), table_name='exception')
    op.drop_table('exception')
    op.drop_index(op.f('ix_approval_event_draft_id'), table_name='approval_event')
    op.drop_table('approval_event')
    op.drop_index(op.f('ix_supplier_sku_sku_id'), table_name='supplier_sku')
    op.drop_index(op.f('ix_supplier_sku_batch_id'), table_name='supplier_sku')
    op.drop_table('supplier_sku')
    op.drop_index(op.f('ix_sku_check_result_run_id'), table_name='sku_check_result')
    op.drop_table('sku_check_result')
    op.drop_index(op.f('ix_po_draft_run_id'), table_name='po_draft')
    op.drop_table('po_draft')
    op.drop_index(op.f('ix_open_po_sku_id'), table_name='open_po')
    op.drop_index(op.f('ix_open_po_batch_id'), table_name='open_po')
    op.drop_table('open_po')
    op.drop_index(op.f('ix_inventory_snapshot_sku_id'), table_name='inventory_snapshot')
    op.drop_index(op.f('ix_inventory_snapshot_batch_id'), table_name='inventory_snapshot')
    op.drop_table('inventory_snapshot')
    op.drop_index(op.f('ix_demand_sku_id'), table_name='demand')
    op.drop_index(op.f('ix_demand_batch_id'), table_name='demand')
    op.drop_table('demand')
    op.drop_index(op.f('ix_supplier_master_batch_id'), table_name='supplier_master')
    op.drop_table('supplier_master')
    op.drop_index(op.f('ix_sku_master_batch_id'), table_name='sku_master')
    op.drop_table('sku_master')
    op.drop_table('procurement_run')
    op.drop_index(op.f('ix_tool_execution_log_tool_name'), table_name='tool_execution_log')
    op.drop_table('tool_execution_log')
    op.drop_table('import_batch')
    # ### end Alembic commands ###
