import { useRef, useState } from 'react'
import { ArrowDownToLine, ArrowRight, ArrowUpRight, CheckCheck, ChevronDown, Clock3, FileSpreadsheet, FileUp, Filter, Layers3, PackageCheck, Pencil, Play, Search, ShieldCheck, Sparkles, Truck, UploadCloud } from 'lucide-react'
import { Badge, Button, dateTime, Empty, money, number, PanelHead, SectionTitle, shortId, TextLink } from './components'
import type { ApprovalEvent, AuditEvent, Batch, Check, Draft, ExceptionItem, Line, Run, Status } from './types'

export type Screen='dashboard'|'data'|'skus'|'exceptions'|'drafts'|'audit'
export function Dashboard({run,results,exceptions,drafts,onGo,onRun,onEvidence,busy}:{run:Run|null;results:Check[];exceptions:ExceptionItem[];drafts:Draft[];onGo:(s:Screen)=>void;onRun:()=>void;onEvidence:(r:Check)=>void;busy:boolean}){
  const open=exceptions.filter(e=>e.status==='OPEN'),blocked=results.filter(r=>r.status==='BLOCKED'),pending=drafts.filter(d=>d.lines.length&&d.status!=='APPROVED')
  const expected=run?.expected_sku_count||0, coverage=expected?Math.round((run?.processed_count||0)/expected*100):0, complete=expected?Math.round(((run?.reorder_count||0)+(run?.no_reorder_count||0))/expected*100):0
  return <><SectionTitle eyebrow="YOUR DAILY PROCUREMENT BRIEF" title="A clear view. A better order." description="Every SKU accounted for. Every purchasing decision ready to review." action={<Button onClick={onRun} disabled={busy}><Play size={16} fill="currentColor"/>Run daily check</Button>}/>
    <div className="overview-banner"><div className="banner-icon"><Layers3 size={27}/></div><div><span className="eyebrow">{run?'LATEST REVIEW':'WELCOME TO SUPPLYDESK'}</span><h2>{run?`${run.processed_count} of ${expected} SKUs checked. ${run.blocked_count?`${run.blocked_count} need your attention.`:'You’re ready for the next step.'}`:'Your procurement day, in one workspace.'}</h2><p>{run?'Recommendations are prepared by the agent. Final orders stay in your hands.':'Load a synthetic scenario or upload your data to begin a complete procurement review.'}</p></div><div className="banner-right">{run?<Badge status={run.status}/>:<Button kind="secondary" onClick={()=>onGo('data')}>Set up your data<ArrowRight size={15}/></Button>}<span><ShieldCheck size={13}/> Human approval required</span></div></div>
    <div className="stats-grid">{[
      {label:'SKUs in this review',value:expected,sub:`${run?.processed_count||0} processed · ${expected} expected`,icon:Layers3,kind:'neutral'},
      {label:'Ready to reorder',value:run?.reorder_count||0,sub:'Validated replenishment decisions',icon:PackageCheck,kind:'green'},
      {label:'No reorder needed',value:run?.no_reorder_count||0,sub:'Covered by stock and timely incoming',icon:CheckCheck,kind:'blue'},
      {label:'Blocked SKUs',value:run?.blocked_count||0,sub:'Visible and waiting for a correction',icon:ShieldCheck,kind:'orange'},
    ].map(m=><div key={m.label} className={`stat-card ${m.kind}`}><div><span>{m.label}</span><m.icon size={20}/></div><strong>{m.value.toString().padStart(2,'0')}</strong><small>{m.sub}</small></div>)}</div>
    <div className="dashboard-grid"><section className="panel"><PanelHead title="Review progress" note="A complete scan can still contain unresolved decisions." action={<span className="micro-label">LIVE RUN STATE</span>}/><div className="progress-pair"><div><span>Scan coverage<strong>{coverage}%</strong></span><div className="progress-track"><i style={{width:`${coverage}%`}}/></div><p>{run?.processed_count||0} of {expected} SKUs evaluated</p></div><div><span>Decision completion<strong>{complete}%</strong></span><div className="progress-track pale"><i style={{width:`${complete}%`}}/></div><p>{(run?.reorder_count||0)+(run?.no_reorder_count||0)} decisions ready · {run?.blocked_count||0} blocked</p></div></div><div className="workflow-strip">{['Data validated','All SKUs checked','Exceptions reviewed','Orders approved'].map((label,i)=>{const done=!!run&&(i===0||i===1&&coverage===100||i===2&&complete===100||i===3&&drafts.length>0&&drafts.every(d=>d.status==='APPROVED'));return <div key={label} className={done?'done':''}><span>{done?<CheckCheck size={14}/>:i+1}</span>{label}</div>})}</div></section>
    <section className="panel next-panel"><span className="eyebrow">NEXT IN YOUR WORKFLOW</span><div className="next-icon"><FileSpreadsheet size={25}/></div><h2>{pending.length?`${pending.length} supplier drafts to review`:'Your next order starts here'}</h2><p>{pending.length?'Review recommendations and delivery dates before giving your explicit approval.':'Valid reorder lines are grouped into one purchase order per default supplier.'}</p><TextLink onClick={()=>onGo(pending.length?'drafts':'data')}>{pending.length?'Open PO drafts':'Go to data intake'}</TextLink></section></div>
    <div className="dashboard-bottom"><section className="panel attention-panel"><PanelHead title="Needs your attention" note={`${open.filter(e=>e.severity==='BLOCKING').length} blocking exceptions · ${open.filter(e=>e.severity==='WARNING').length} timing warnings`} action={<TextLink onClick={()=>onGo('exceptions')}>View exceptions</TextLink>}/>{blocked.length?<div className="attention-list">{blocked.slice(0,4).map(r=><button key={r.id} className="attention-row" onClick={()=>onEvidence(r)}><span className="item-icon"><FileSpreadsheet size={18}/></span><span><strong>{r.context.sku.description}</strong><small>{r.sku_id} · {open.find(e=>e.result_id===r.id&&e.severity==='BLOCKING')?.code.replaceAll('_',' ').toLowerCase()||r.decision_reason}</small></span><Badge status="BLOCKED"/><ArrowUpRight size={16}/></button>)}</div>:<Empty title={run?'No blocked SKUs':'No review started yet'}>{run?'All evaluated SKUs have an actionable decision. Review any timing warnings before approval.':'Start a daily check to see issues here.'}</Empty>}</section>
    <section className="panel"><PanelHead title="Supplier drafts" note="One draft per supplier, per review." action={<TextLink onClick={()=>onGo('drafts')}>View all</TextLink>}/>{drafts.filter(d=>d.lines.length).length?<div className="supplier-list">{drafts.filter(d=>d.lines.length).map(d=><button key={d.id} onClick={()=>onGo('drafts')}><span className="supplier-avatar">{d.supplier_id.slice(-1)}</span><span><strong>{d.supplier_name}</strong><small>{d.lines.length} lines · {d.currency} {money(d.total)}</small></span><Badge status={d.status}/></button>)}</div>:<Empty title="No purchase orders yet">Run the procurement check to prepare eligible supplier drafts.</Empty>}</section></div>
    <div className="page-foot"><span><ShieldCheck size={14}/> Synthetic office-supplies workspace · pre-tax values</span><span>{run?`Last review ${dateTime(run.created_at)}`:'Your original source data stays intact'}</span></div>
  </>
}

export function DataScreen({batches,busy,onUpload,onDemo,onRun}:{batches:Batch[];busy:boolean;onUpload:(files:File[])=>Promise<void>;onDemo:(s:string)=>void;onRun:(batch:Batch)=>void}){
  const input=useRef<HTMLInputElement>(null),[files,setFiles]=useState<File[]>([]),[drag,setDrag]=useState(false)
  return <><SectionTitle eyebrow="START WITH RELIABLE INPUTS" title="Data intake" description="Bring the six source tables together. Review validation before you run."/>
    <div className="demo-grid">{[{id:'normal',num:'01',title:'A normal procurement day',text:'Ten SKUs. Qualified suppliers. Review the resulting purchase orders.',icon:PackageCheck},{id:'incoming',num:'02',title:'Incoming stock, checked',text:'See timely stock avoid a reorder—and a late PO expose a timing gap.',icon:Truck},{id:'exceptions',num:'03',title:'Find it. Fix it. Recheck.',text:'Missing price, missing inventory and an unapproved supplier mapping.',icon:ShieldCheck}].map(s=><button disabled={busy} className="demo-card" key={s.id} onClick={()=>onDemo(s.id)}><div><s.icon size={21}/><span>SCENARIO {s.num}</span></div><h3>{s.title}</h3><p>{s.text}</p><span className="text-link">Load synthetic scenario<ArrowRight size={15}/></span></button>)}</div>
    <section className="panel upload-panel"><PanelHead title="Upload your dataset" note="Six CSV files, one six-sheet Excel workbook, or one dataset JSON."/><div className={`dropzone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);setFiles(Array.from(e.dataTransfer.files))}}><UploadCloud size={37} strokeWidth={1.4}/><h3>Drop your source files here</h3><p>CSV, XLSX or JSON · up to 10 MB per upload</p><Button kind="secondary" onClick={()=>input.current?.click()} disabled={busy}><FileUp size={16}/>Browse files</Button><input ref={input} type="file" multiple hidden accept=".csv,.xlsx,.json" aria-label="Upload source files" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></div>
      {!!files.length&&<div className="selected-files">{files.map((f,i)=><span key={i}><FileSpreadsheet size={15}/>{f.name}<small>{(f.size/1024).toFixed(1)} KB</small></span>)}<Button disabled={busy} onClick={()=>void onUpload(files).then(()=>setFiles([])).catch(()=>{})}>{busy?'Validating…':'Upload & validate'}</Button></div>}
      <div className="source-chips">{['SKU & stock rules','Inventory','Demand','Open POs','Supplier master','Supplier mapping'].map(t=><span key={t}>{t}</span>)}</div><p className="muted small">All six tables are required. Empty demand or open-PO tables must still include headers. Missing commercial values are reported, never filled automatically.</p>
    </section>
    <section className="panel"><PanelHead title="Import history" note="Original data and validation issues remain available for review."/>{batches.length?<div className="batch-list">{batches.map(b=><details key={b.id} className="batch"><summary><span className="item-icon"><FileSpreadsheet size={19}/></span><span className="batch-name"><strong>{b.filename}</strong><small>{dateTime(b.created_at)} · {shortId(b.id)}</small></span><Badge status={b.status}/><span className="issue-count">{b.issues.length} issues</span><ChevronDown size={16}/></summary><div className="batch-details">{b.issues.length?<div className="table-scroll"><table><thead><tr><th>Source / row</th><th>Field</th><th>Original value</th><th>Validation finding</th></tr></thead><tbody>{b.issues.map((e,i)=><tr key={i}><td>{e.table||'Dataset'}{e.row?` / ${e.row}`:''}</td><td>{e.field||'—'}</td><td>{e.original||'—'}</td><td>{e.message}</td></tr>)}</tbody></table></div>:<p className="muted">Structure validated. Business exceptions, if any, will be identified during the SKU check.</p>}{b.status.startsWith('VALIDATED')&&<Button kind="secondary" onClick={()=>onRun(b)} disabled={busy}>Run check with this batch<ArrowRight size={15}/></Button>}</div></details>)}</div>:<Empty title="No imports yet">Load a scenario above or upload your source files.</Empty>}</section>
  </>
}

export function SKUScreen({results,run,onEvidence}:{results:Check[];run:Run|null;onEvidence:(r:Check)=>void}){
  const [filter,setFilter]=useState<Status|'ALL'>('ALL'),[search,setSearch]=useState('')
  const visible=results.filter(r=>(filter==='ALL'||r.status===filter)&&`${r.sku_id} ${r.context.sku.description}`.toLowerCase().includes(search.toLowerCase()))
  return <><SectionTitle eyebrow="NOTHING SILENTLY SKIPPED" title="SKU check" description="Every expected SKU, with an explicit decision and the evidence behind it."/>
    <section className="panel"><div className="table-toolbar"><div className="tabs">{(['ALL','REORDER','NO_REORDER','BLOCKED'] as const).map(s=><button className={filter===s?'active':''} onClick={()=>setFilter(s)} key={s}>{s==='ALL'?'All SKUs':s==='NO_REORDER'?'No reorder':s==='REORDER'?'Reorder':'Blocked'}<span>{s==='ALL'?results.length:results.filter(r=>r.status===s).length}</span></button>)}</div><label className="search"><Search size={16}/><input placeholder="Find a SKU or product" aria-label="Search SKUs" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
    <div className="table-caption"><span>{visible.length} shown · {results.length} stored · {run?.expected_sku_count||0} expected</span>{run&&run.processed_count<run.expected_sku_count&&<span className="orange-text">Check not complete. Pending SKUs have no confirmed decision.</span>}<span><Filter size={13}/> Filters only change this view</span></div>
    <div className="table-scroll"><table className="sku-table"><thead><tr><th>SKU / product</th><th>Decision</th><th>On hand</th><th>Incoming</th><th>Demand</th><th>Projected</th><th>Order qty</th><th>Decision reason</th><th/></tr></thead><tbody>{visible.map(r=><tr key={r.id} className={r.status==='BLOCKED'?'blocked-row':''}><td><button className="sku-name" onClick={()=>onEvidence(r)}><strong>{r.context.sku.description}</strong><small>{r.sku_id}</small></button></td><td><Badge status={r.revision===0?'CREATED':r.status}/></td><td>{number(r.on_hand)}</td><td>{number(r.valid_incoming)}</td><td>{number(r.demand_qty)}</td><td className={r.projected_stock!==null&&r.projected_stock<0?'orange-text':''}>{number(r.projected_stock)}</td><td><strong>{number(r.final_order_qty)}</strong></td><td className="reason-cell">{r.decision_reason}</td><td><button className="icon-button" aria-label={`View evidence for ${r.sku_id}`} onClick={()=>onEvidence(r)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>{!visible.length&&<Empty title="No matching SKU results">{results.length?'Try another search or status filter.':'Start a check to populate every active SKU here.'}</Empty>}
    <div className="panel-footer">Incoming, demand and projected stock refer to the binding need date. Open a row to review the full dated timeline.</div></section></>
}

export function ExceptionScreen({exceptions,results,onResolve,onEvidence}:{exceptions:ExceptionItem[];results:Check[];onResolve:(e:ExceptionItem,r:Check)=>void;onEvidence:(r:Check)=>void}){
  const [history,setHistory]=useState(false),[onlyBlocked,setOnlyBlocked]=useState(false)
  const items=exceptions.filter(e=>(history||e.status==='OPEN')&&(!onlyBlocked||e.severity==='BLOCKING')).sort((a,b)=>Number(b.severity==='BLOCKING')-Number(a.severity==='BLOCKING'))
  return <><SectionTitle eyebrow="A CLEAR PATH TO RESOLUTION" title="Exception center" description="Unresolved items stay here until the backend confirms the correction."/>
    <div className="exception-toolbar"><div><button className={`chip-button ${!onlyBlocked?'active':''}`} onClick={()=>setOnlyBlocked(false)}>All exceptions</button><button className={`chip-button ${onlyBlocked?'active':''}`} onClick={()=>setOnlyBlocked(true)}>Blocking only</button></div><label className="checkbox"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/>Show resolved / superseded</label></div>
    <div className="exceptions-grid">{items.map(e=>{const r=results.find(r=>r.id===e.result_id);return <article className={`exception-card ${e.severity==='WARNING'?'warning-card':''}`} key={e.id}><div className="exception-top"><Badge status={e.severity}/><Badge status={e.status}/></div><span className="eyebrow">{r?.sku_id||'SKU source'} · {r?.context.sku.description}</span><h3>{e.code.toLowerCase().replaceAll('_',' ')}</h3><p>{e.message}</p><div className="exception-detail"><span>Field needing attention</span><code>{e.required_field}</code><span>Required action</span><p>{e.required_action}</p></div><div className="exception-actions">{r&&<TextLink onClick={()=>onEvidence(r)}>View source evidence</TextLink>}{r&&e.status==='OPEN'&&<Button kind={e.severity==='BLOCKING'?'primary':'secondary'} onClick={()=>onResolve(e,r)}>{e.severity==='BLOCKING'?'Resolve issue':'Review source'}</Button>}</div></article>})}</div>{!items.length&&<section className="panel"><Empty title="No exceptions in this view">Any blocking issues and timing warnings from the current run will appear here.</Empty></section>}</>
}

export function DraftScreen({drafts,busy,onEdit,onReview,onExport,onEvidence,onHistory,onSync}:{drafts:Draft[];busy:boolean;onEdit:(d:Draft,l:Line)=>void;onReview:(d:Draft,reject:boolean)=>void;onExport:(d:Draft)=>void;onEvidence:(id:string)=>void;onHistory:(d:Draft)=>void;onSync:()=>void}){
  return <><SectionTitle eyebrow="PREPARED BY THE AGENT. APPROVED BY YOU." title="Purchase order drafts" description="Review each supplier’s order and timing before final approval." action={<Button kind="secondary" onClick={onSync} disabled={busy}><Layers3 size={16}/>Sync drafts</Button>}/>
    {!drafts.length&&<section className="panel"><Empty title="No eligible drafts yet">Complete a procurement check. Blocked SKUs cannot enter a purchase order.</Empty></section>}
    <div className="draft-list">{drafts.map(d=><section className="panel draft-card" key={d.id}><div className="draft-heading"><div className="supplier-avatar large">{d.supplier_id.slice(-1)}</div><div><span className="eyebrow">{d.supplier_id} · PO-{shortId(d.id)}</span><h2>{d.supplier_name}</h2><p>Run {shortId(d.run_id)} · {d.order_date} · {d.warehouse} · version {d.version}</p></div><div className="draft-total"><Badge status={d.status}/><strong><small>{d.currency}</small> {money(d.total)}</strong><span>Pre-tax · {d.lines.length} lines</span></div></div>
    {d.status==='NEEDS_REVIEW'&&<div className="draft-notice">Review required. The current quantity, price or source version must be explicitly approved. Any earlier approval does not apply.</div>}
    <div className="table-scroll"><table><thead><tr><th>SKU / description</th><th>Quantity</th><th>UOM</th><th>Unit price</th><th>Line amount</th><th>Need by</th><th>Expected delivery</th><th>Source</th><th/></tr></thead><tbody>{d.lines.map(l=><tr key={l.id}><td><strong>{l.description}</strong><small className="block">{l.sku_id}</small></td><td>{number(l.quantity)}</td><td>{l.uom}</td><td>{money(l.unit_price)}</td><td><strong>{money(l.amount)}</strong></td><td>{l.need_date}</td><td>{l.expected_delivery_date}</td><td><button className="source-link" onClick={()=>onEvidence(l.result_id)}>{shortId(l.result_id)} · v{l.result_revision}<ArrowUpRight size={13}/></button></td><td><button disabled={busy} className="icon-button" aria-label={`Edit ${l.sku_id} line`} onClick={()=>onEdit(d,l)}><Pencil size={15}/></button></td></tr>)}</tbody></table></div>
    {!d.lines.length&&<p className="empty-draft">All source lines were removed or superseded. This empty draft cannot be approved or exported.</p>}
    <div className="draft-footer"><div>{d.approved_at?<><span className="approved-by"><ShieldCheck size={15}/>Approved by {d.reviewer}</span><small>{dateTime(d.approved_at)}</small></>:<span className="muted"><Clock3 size={15}/> Awaiting explicit human review</span>}<button className="text-link" onClick={()=>onHistory(d)}>Approval history<ArrowUpRight size={13}/></button></div><div className="actions">{d.status==='APPROVED'?<Button onClick={()=>onExport(d)} disabled={busy}><ArrowDownToLine size={16}/>Export approved PO</Button>:<><Button kind="secondary" disabled={busy||!d.lines.length||d.status==='REJECTED'} onClick={()=>onReview(d,true)}>Reject</Button><Button disabled={busy||!d.lines.length} onClick={()=>onReview(d,false)}><ShieldCheck size={16}/>Review & approve</Button></>}</div></div>
    </section>)}</div>
  </>
}

export function AuditScreen({run,runs,batches,events,onRun,onMore,busy}:{run:Run|null;runs:Run[];batches:Batch[];events:AuditEvent[];onRun:(id:string)=>void;onMore:()=>void;busy:boolean}){
  const [scope,setScope]=useState<'all'|'run'>('run'),[open,setOpen]=useState<string|null>(null)
  const visible=events.filter(e=>scope==='all'||run&&(JSON.stringify(e.input).includes(run.id)||JSON.stringify(e.output).includes(run.id)))
  const batch=batches.find(b=>b.id===run?.batch_id)
  return <><SectionTitle eyebrow="THE STORY BEHIND EVERY DECISION" title="Audit & run history" description="Persistent input versions, confirmed actions and failed operations—without reconstructed guesses."/>
    <div className="audit-summary"><section className="panel"><PanelHead title="Current review"/>{run?<dl className="detail-list"><dt>Run ID</dt><dd>{run.id}</dd><dt>Started</dt><dd>{dateTime(run.created_at)}</dd><dt>Input batch</dt><dd>{batch?.filename||run.batch_id}</dd><dt>Input version</dt><dd>{batch?.source_hash||'Not available in loaded history'}</dd><dt>Policy</dt><dd>{run.horizon} days · {run.currency} · {run.warehouse}</dd><dt>Coverage</dt><dd>{run.processed_count}/{run.expected_sku_count} scanned · {run.blocked_count} blocked</dd></dl>:<Empty title="No current run">Start a review first.</Empty>}</section><section className="panel evaluation-note"><Sparkles size={22}/><h3>Measure what actually happened.</h3><p>Run and approval timestamps come from the backend. Decision coverage is distinct from decision completion.</p><p>Manual baseline, task-open time and paired correctness scores have not been recorded. No time-saving or accuracy claim is inferred from these logs.</p><span className="micro-label">CORRECTNESS → EXCEPTIONS → APPROVAL → TRACEABILITY</span></section></div>
    <section className="panel"><PanelHead title="Procurement runs" note="Reopen a saved review without creating another run."/><div className="table-scroll"><table><thead><tr><th>Run</th><th>Created</th><th>Status</th><th>Coverage</th><th>Reorder</th><th>Blocked</th><th/></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td>{shortId(r.id)}</td><td>{dateTime(r.created_at)}</td><td><Badge status={r.status}/></td><td>{r.processed_count}/{r.expected_sku_count}</td><td>{r.reorder_count}</td><td>{r.blocked_count}</td><td><TextLink onClick={()=>onRun(r.id)}>Open review</TextLink></td></tr>)}</tbody></table></div></section>
    <section className="panel"><PanelHead title="Action timeline" note="Newest first. Failed actions are never marked as successful." action={<select aria-label="Audit scope" value={scope} onChange={e=>setScope(e.target.value as 'all'|'run')}><option value="run">Current run references</option><option value="all">All workspace actions</option></select>}/><div className="audit-list">{visible.map(e=><div className="audit-event" key={e.id}><button onClick={()=>setOpen(open===e.id?null:e.id)}><span className={`timeline-dot ${e.status==='FAILED'?'failed':''}`}/><div><strong>{e.tool_name.replaceAll('_',' ')}</strong><span>{e.actor} · {dateTime(e.created_at)}</span></div><Badge status={e.status}/><ChevronDown size={15}/></button>{open===e.id&&<div className="audit-detail">{e.error&&<p className="orange-text">{e.error}</p>}<strong>Recorded input</strong><pre>{JSON.stringify(e.input,null,2)}</pre><strong>Confirmed output</strong><pre>{JSON.stringify(e.output,null,2)}</pre></div>}</div>)}</div>{!visible.length&&<p className="empty-draft">No matching events in this page. Load earlier actions or switch to all workspace actions.</p>}<div className="panel-footer"><Button kind="secondary" onClick={onMore} disabled={busy}>Load earlier actions</Button></div></section>
  </>
}
export function History({events}:{events:ApprovalEvent[]}){return events.length?<div className="history-list">{[...events].sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(e=><div key={e.id}><Badge status={e.action}/><strong>{e.actor}</strong><small>{dateTime(e.created_at)} · version {e.version}</small><p>{e.comment}</p></div>)}</div>:<Empty title="No review events yet">Approvals, rejections, invalidations and exports will be recorded here.</Empty>}
